SET search_path TO smart_shell;

-- SELECT current_schema();

DROP TABLE IF EXISTS TBL_DOCUMENT_DETAIL;

DROP TABLE IF EXISTS TBL_DOCUMENT_HEADER;

CREATE TABLE TBL_DOCUMENT_HEADER(
    IDC0MPANY INTEGER,
    -- GENERAL
    NUMINT BIGINT,   
    CODEXT VARCHAR(100),
    TYPCOMDOC INTEGER,
    SITCOMDOC INTEGER,
	SERIE VARCHAR(5),
    NUMDOC BIGINT,
	-- RELACIONADO A LA EMISION DEL DOCUMENT
    REGISTDATE DATE,
	CODBRANCH INTEGER,
	CODPLAISS INTEGER,
	-- MOTIVO
    INGSALCOM INTEGER,
    REACOMDOC INTEGER,
	-- MONEDA Y TYPO DE CAMBIO
    CODCUR VARCHAR(5),
    EXCHANGERATE NUMERIC(8,4),
    -- CLIENTE
    CODBUSPAR VARCHAR(50),
	BUSNAM VARCHAR(250),
	ADDRES VARCHAR(250),
	POSCOD VARCHAR(20),
	-- VENDEDOR
	CODSEL VARCHAR(50),
	-- CONDICION DE PAGO
	TYPPAYCON INTEGER,
    -- TRIBUTO
    INCIGV INTEGER,
    TASIGV NUMERIC(8,4),
    -- IMPORTES
    IMPAFECTO NUMERIC(24,4),
    IMPINAFECTO NUMERIC(24,4),
    IMPEXONERADO NUMERIC(24,4),
    IMPGRATUITO NUMERIC(24,4),
    IMPIGV NUMERIC(24,4),
    IMPISC NUMERIC(24,4),
    IMPTRIBADD01 NUMERIC(24,4),
    IMPTRIBADD02 NUMERIC(24,4),
    IMPTRIBADD03 NUMERIC(24,4),
    IMPTRIBADD04 NUMERIC(24,4),
    IMPDESC01 NUMERIC(24,4),
    IMPDESC02 NUMERIC(24,4),
    IMPDESC03 NUMERIC(24,4),
    IMPDESC04 NUMERIC(24,4),
	IMPLISTPRICE NUMERIC(24,4),
    IMPDESCTOTAL NUMERIC(24,4),
    IMPSALEPRICE NUMERIC(24,4),
	IMPTRIBTOTAL NUMERIC(24,4),
    IMPTOTAL NUMERIC(24,4),
	-- EXTRA
	REFERE VARCHAR(1000),
	OBSERV VARCHAR(1000),
	COMMEN VARCHAR(1000),
    -- ARCHIVOS
    ARCPDF BYTEA,
    ARCCRD BYTEA,
    ARCXML BYTEA,
    -- AUDITORIA
	STATUS VARCHAR(1) DEFAULT 'Y',
	CREATEBY VARCHAR(10) DEFAULT 'ADMIN',
	UPDATEBY VARCHAR(10) DEFAULT 'ADMIN',
	CREATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP	
);

ALTER TABLE TBL_DOCUMENT_HEADER
    ADD CONSTRAINT PK_DOCUMENT_HEADER PRIMARY KEY (IDC0MPANY,NUMINT);

SELECT * FROM  TBL_DOCUMENT_HEADER;

CREATE TABLE TBL_DOCUMENT_DETAIL(
    IDC0MPANY INTEGER,
    -- GENERAL
    NUMINT BIGINT,   
    NUMITE BIGINT,
    TYPINV INTEGER,
    CODART VARCHAR(50),
    ETIQUETA BIGINT,
	QUANTITY NUMERIC(24,4),
	PRICE NUMERIC(24,4),
    -- IMPORTE
    IMPAFECTO NUMERIC(24,4),
    IMPINAFECTO NUMERIC(24,4),
    IMPEXONERADO NUMERIC(24,4),
    IMPGRATUITO NUMERIC(24,4),
    IMPIGV NUMERIC(24,4),
    IMPISC NUMERIC(24,4),
    IMPTRIBADD01 NUMERIC(24,4),
    IMPTRIBADD02 NUMERIC(24,4),
    IMPTRIBADD03 NUMERIC(24,4),
    IMPTRIBADD04 NUMERIC(24,4),
    IMPDESC01 NUMERIC(24,4),
    IMPDESC02 NUMERIC(24,4),
    IMPDESC03 NUMERIC(24,4),
    IMPDESC04 NUMERIC(24,4),
	IMPLISTPRICE NUMERIC(24,4),
    IMPDESCTOTAL NUMERIC(24,4),
    IMPSALEPRICE NUMERIC(24,4),
	IMPTRIBTOTAL NUMERIC(24,4),
    IMPTOTAL NUMERIC(24,4),
    -- AUDITORIA
	STATUS VARCHAR(1) DEFAULT 'Y',
	CREATEBY VARCHAR(10) DEFAULT 'ADMIN',
	UPDATEBY VARCHAR(10) DEFAULT 'ADMIN',
	CREATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP	
);

ALTER TABLE TBL_DOCUMENT_DETAIL
    ADD CONSTRAINT PK_DOCUMENT_DETAIL PRIMARY KEY (IDC0MPANY,NUMINT,NUMITE);
	
ALTER TABLE TBL_DOCUMENT_DETAIL
    ADD CONSTRAINT FK_DOCUMENT_HEADER FOREIGN KEY (IDC0MPANY,NUMINT)
        REFERENCES TBL_DOCUMENT_HEADER (IDC0MPANY,NUMINT);

SELECT * FROM  TBL_DOCUMENT_DETAIL;