version: '3.8'  # Puedes ajustar la versión según la que desees usar

services:
  postgres:
    container_name: postgres-smart-shell
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1073741824
      POSTGRES_DB: smart-shell
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - smart-shell-net  # Conexión a la red smart-shell-net

networks:
  smart-shell-net:  # Definición de la red smart-shell-net
    external: true   # Indicador de que la red ya está creada externamente
deploy:
  resources:
    limits:
      memory: 2G # Límite de memoria para el contenedor