services:
  app:
    container_name: smart-shell-postgres
    env_file:
      - ./.env
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - /var/www/volumes/smart-shell/smart-shell-postgres/data:/var/lib/postgresql/data
      - /var/www/volumes/smart-shell/smart-shell-postgres/logs:/opt/logs
      - /var/www/volumes/smart-shell/smart-shell-postgres/backups:/opt/backups
      - /var/www/volumes/smart-shell/smart-shell-postgres/configurations:/opt/configurations
    networks:
      - smart-shell-net

networks:
  smart-shell-net:
    external: true