services:
  app:
    container_name: smart-shell-postgres
    env_file:
      - ./.env
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        POSTGRES_DB: $SMART_SHELL_POSTGRES_DATABASE
    environment:
      POSTGRES_USER: $SMART_SHELL_POSTGRES_USERNAME
      POSTGRES_PASSWORD: $SMART_SHELL_POSTGRES_PASSWORD
      POSTGRES_DB: $SMART_SHELL_POSTGRES_DATABASE
    ports:
      - "${SMART_SHELL_POSTGRES_PORT}:5432"
    volumes:
      - /var/www/volumes/smart-shell/smart-shell-postgres/data:/var/lib/postgresql/data
      - /var/www/volumes/smart-shell/smart-shell-postgres/logs:/opt/logs
      - /var/www/volumes/smart-shell/smart-shell-postgres/backups:/opt/backups
      - /var/www/volumes/smart-shell/smart-shell-postgres/configurations:/opt/configurations
    networks:
      - smart-shell-net
    restart: unless-stopped

networks:
  smart-shell-net:
    external: true