services:
  app:
    container_name: smart-shell-postgres
    env_file:
      - ./.env
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: $SMART_SHELL_POSTGRES_USERNAME
      POSTGRES_PASSWORD: $SMART_SHELL_POSTGRES_PASSWORD
      POSTGRES_DB: $SMART_SHELL_POSTGRES_DATABASE
    ports:
      - "${SMART_SHELL_POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/opt/logs
      - postgres-backups:/opt/backups
      - postgres-configurations:/opt/configurations
    networks:
      - smart-shell-net
    restart: unless-stopped

volumes:
  postgres-data:
  postgres-logs:
  postgres-backups:
  postgres-configurations:

networks:
  smart-shell-net:
    external: true