version: '3.8'  # Puedes ajustar la versión según la que desees usar

services:
  postgres:
    container_name: postgres-smart-shell
    env_file:
      - ./.env
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ./logs:/opt/logs
      - ./backups:/opt/backups
    networks:
      - smart-shell-net  # Conexión a la red smart-shell-net

networks:
  smart-shell-net:  # Definición de la red smart-shell-net
    external: true   # Indicador de que la red ya está creada externamente