SET search_path TO smart_shell;

-- SELECT current_schema();

DROP TABLE IF EXISTS TBL_DOCUMENT_DETAIL;

DROP TABLE IF EXISTS TBL_DOCUMENT_HEADER;

DROP TABLE IF EXISTS TBL_DOCUMENT_KARDEX;

CREATE TABLE TBL_DOCUMENT_HEADER(
    IDCOMPANY INTEGER,
    -- GENERAL
    NUMINT BIGINT,   
    CODEXT VARCHAR(100),
    TYPCOMDOC INTEGER,
    SITCOMDOC INTEGER,
	SERIE VARCHAR(5),
    NUMDOC BIGINT,
	-- RELACIONADO A LA EMISION DEL DOCUMENT
    REGISTDATE DATE DEFAULT CURRENT_DATE,
	CODBRANCH INTEGER DEFAULT 1,
    ORIWAREHOUSE INTEGER DEFAULT 1,
    DESWAREHOUSE INTEGER DEFAULT 0,
	CODPLAISS INTEGER,
	-- MOTIVO
    INOUT INTEGER,
    REACOMDOC INTEGER,
	-- MONEDA Y TYPO DE CAMBIO
    CODCUR VARCHAR(5),
    EXCHANGERATE NUMERIC(8,4) DEFAULT 1,
    EXCHANGERATE01 NUMERIC(8,4) DEFAULT 1,
    EXCHANGERATE02 NUMERIC(8,4) DEFAULT 1,
    -- CLIENTE
    CODBUSPAR VARCHAR(50),
	BUSNAM VARCHAR(250),
	ADDRES VARCHAR(250),
	POSCOD VARCHAR(20),
	-- VENDEDOR
	CODSEL VARCHAR(50),
	-- CONDICION DE PAGO
	TYPPAYCON INTEGER,
    -- TRIBUTO
    INCIGV INTEGER DEFAULT 1,
    TASIGV NUMERIC(8,4),
    -- IMPORTES
    IMPAFECTO NUMERIC(24,4),
    IMPINAFECTO NUMERIC(24,4),
    IMPEXONERADO NUMERIC(24,4),
    IMPGRATUITO NUMERIC(24,4),
    IMPIGV NUMERIC(24,4),
    IMPISC NUMERIC(24,4),
    IMPTRIBADD01 NUMERIC(24,4),
    IMPTRIBADD02 NUMERIC(24,4),
    IMPTRIBADD03 NUMERIC(24,4),
    IMPTRIBADD04 NUMERIC(24,4),
    IMPDESC01 NUMERIC(24,4),
    IMPDESC02 NUMERIC(24,4),
    IMPDESC03 NUMERIC(24,4),
    IMPDESC04 NUMERIC(24,4),
	IMPLISTPRICE NUMERIC(24,4),
    IMPDESCTOTAL NUMERIC(24,4),
    IMPSALEPRICE NUMERIC(24,4),
	IMPTRIBTOTAL NUMERIC(24,4),
    IMPTOTAL NUMERIC(24,4),
	-- EXTRA
	REFERE VARCHAR(1000),
	OBSERV VARCHAR(1000),
	COMMEN VARCHAR(1000),
    -- ARCHIVOS
    ARCPDF BYTEA,
    ARCCRD BYTEA,
    ARCXML BYTEA,
    -- AUDITORIA
	STATUS VARCHAR(1) DEFAULT 'Y',
	CREATEBY VARCHAR(10) DEFAULT 'ADMIN',
	UPDATEBY VARCHAR(10) DEFAULT 'ADMIN',
	CREATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP	
);

ALTER TABLE TBL_DOCUMENT_HEADER
    ADD CONSTRAINT PK_DOCUMENT_HEADER PRIMARY KEY (IDCOMPANY,NUMINT);

SELECT * FROM  TBL_DOCUMENT_HEADER;

CREATE TABLE TBL_DOCUMENT_DETAIL(
    IDCOMPANY INTEGER,
    -- GENERAL
    NUMINT BIGINT,   
    NUMITE BIGINT,
    TYPINV INTEGER,
    CODART VARCHAR(50),
    ETIQUETA BIGINT,
	QUANTITY NUMERIC(24,4),
	PRICE NUMERIC(24,4),
    -- WAREHOUSE
    REGISTDATE DATE DEFAULT CURRENT_DATE,
	CODBRANCH INTEGER DEFAULT 1,
    ORIWAREHOUSE INTEGER DEFAULT 1,
    DESWAREHOUSE INTEGER DEFAULT 0,
    -- IMPORTE
    IMPAFECTO NUMERIC(24,4),
    IMPINAFECTO NUMERIC(24,4),
    IMPEXONERADO NUMERIC(24,4),
    IMPGRATUITO NUMERIC(24,4),
    IMPIGV NUMERIC(24,4),
    IMPISC NUMERIC(24,4),
    IMPTRIBADD01 NUMERIC(24,4),
    IMPTRIBADD02 NUMERIC(24,4),
    IMPTRIBADD03 NUMERIC(24,4),
    IMPTRIBADD04 NUMERIC(24,4),
    IMPDESC01 NUMERIC(24,4),
    IMPDESC02 NUMERIC(24,4),
    IMPDESC03 NUMERIC(24,4),
    IMPDESC04 NUMERIC(24,4),
	IMPLISTPRICE NUMERIC(24,4),
    IMPDESCTOTAL NUMERIC(24,4),
    IMPSALEPRICE NUMERIC(24,4),
	IMPTRIBTOTAL NUMERIC(24,4),
    IMPTOTAL NUMERIC(24,4),
    -- AUDITORIA
	STATUS VARCHAR(1) DEFAULT 'Y',
	CREATEBY VARCHAR(10) DEFAULT 'ADMIN',
	UPDATEBY VARCHAR(10) DEFAULT 'ADMIN',
	CREATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP	
);

ALTER TABLE TBL_DOCUMENT_DETAIL
    ADD CONSTRAINT PK_DOCUMENT_DETAIL PRIMARY KEY (IDCOMPANY,NUMINT,NUMITE);
	
ALTER TABLE TBL_DOCUMENT_DETAIL
    ADD CONSTRAINT FK_DOCUMENT_HEADER FOREIGN KEY (IDCOMPANY,NUMINT)
        REFERENCES TBL_DOCUMENT_HEADER (IDCOMPANY,NUMINT);

SELECT * FROM  TBL_DOCUMENT_DETAIL;

CREATE TABLE TBL_DOCUMENT_KARDEX(
    IDCOMPANY INTEGER,
    LOCALI BIGINT,
    -- GENERAL
    NUMINT BIGINT,   
    NUMITE BIGINT,
    TYPINV INTEGER,
    CODART VARCHAR(50),
    ETIQUETA BIGINT,
	QUANTITY NUMERIC(24,4),
	PRICE NUMERIC(24,4),
    -- REASON
    TYPCOMDOC INTEGER,
    INOUT INTEGER,
    REACOMDOC INTEGER,
    -- WAREHOUSE
	CODBRANCH INTEGER DEFAULT 1,
    ORIWAREHOUSE INTEGER DEFAULT 1,
    DESWAREHOUSE INTEGER DEFAULT 0,
	-- RELACIONADO A LA EMISION DEL DOCUMENT
    REGISTDATE DATE,
    YEAR INTEGER,
    MONTH INTEGER,
    -- IMPORTE
	IMPLISTPRICE01 NUMERIC(24,4),
    IMPLISTPRICE02 NUMERIC(24,4),
    IMPDESCTOTAL01 NUMERIC(24,4),
    IMPDESCTOTAL02 NUMERIC(24,4),
    IMPSALEPRICE01 NUMERIC(24,4),
    IMPSALEPRICE02 NUMERIC(24,4),
	IMPTRIBTOTAL01 NUMERIC(24,4),
	IMPTRIBTOTAL02 NUMERIC(24,4),
    IMPTOTAL01 NUMERIC(24,4),
    IMPTOTAL02 NUMERIC(24,4),
    -- COSTO
    COSRAWMATERIAL01 NUMERIC(24,4),
    COSRAWMATERIAL02 NUMERIC(24,4),
    COSMANUFACTURING01 NUMERIC(24,4),
    COSMANUFACTURING02 NUMERIC(24,4),
    COSLABOUR01 NUMERIC(24,4),
    COSLABOUR02 NUMERIC(24,4),
    COSTRANSPORT01 NUMERIC(24,4),
    COSTRANSPORT02 NUMERIC(24,4),
    COSTOTAL01 NUMERIC(24,4),
    COSTOTAL02 NUMERIC(24,4),
    -- TYPE METHOD FOR COST
    TYPMETHODCOST INTEGER DEFAULT 0,
    -- AUDITORIA
	STATUS VARCHAR(1) DEFAULT 'Y',
	CREATEBY VARCHAR(10) DEFAULT 'ADMIN',
	UPDATEBY VARCHAR(10) DEFAULT 'ADMIN',
	CREATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP	
);

ALTER TABLE TBL_DOCUMENT_KARDEX
    ADD CONSTRAINT PK_DOCUMENT_KARDEX PRIMARY KEY (IDCOMPANY,LOCALI);

SELECT * FROM  TBL_DOCUMENT_KARDEX;