apiVersion: v1
kind: Service
metadata:
  name: postgres-external-service
  namespace: smart-shell-production
  annotations:
    metallb.universe.tf/allow-shared-ip: "192.168.100.241"
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.100.241
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres