apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: smart-shell-production
spec:
  # This MUST match the name of the Headless Service defined above.
  # It tells the StatefulSet which service controls the network domain for its pods.
  serviceName: "postgres-service"
  replicas: 1 # Start with one replica for a simple setup
  
  # The StatefulSet's own selector. It will manage any pods that
  # have the label "app: postgres".
  selector:
    matchLabels:
      app: postgres
      
  # This is the template used to create the Pods.
  template:
    metadata:
      # These are the labels applied to each Pod created by this StatefulSet.
      # This MUST match the `selector.matchLabels` above. This is the most
      # common point of confusion:
      #   - `StatefulSet.spec.selector` says "I am looking for pods with this label."
      #   - `StatefulSet.spec.template.metadata.labels` says "Create pods with this label."
      # They must match for the StatefulSet to manage its own pods.
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: luis122448/smart-shell-postgres:latest
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          # Mount the persistent volume inside the container.
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              
  # This template defines the PersistentVolumeClaim (PVC) for each pod.
  # When a pod like `postgres-statefulset-0` is created, a PVC named
  # `postgres-storage-postgres-statefulset-0` will be automatically created
  # and bound to a PersistentVolume, ensuring data persistence.
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "nas-002"
        resources:
          requests:
            storage: 5Gi # Request 5 Gigabytes of storage